<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class PasswordChangeOtpNotification extends Notification
{
    use Queueable;

    public function __construct(
        public readonly string $otp,
        public readonly int $expiresInMinutes = 10
    ) {
    }

    /**
     * Get the notification's delivery channels.
     *
     * @return array<int, string>
     */
    public function via(object $notifiable): array
    {
        return ['mail'];
    }

    /**
     * Get the mail representation of the notification.
     */
    public function toMail(object $notifiable): MailMessage
    {
        return (new MailMessage)
            ->subject('[SPMO Security] Password Change Verification Code')
            ->greeting('Hello ' . $notifiable->name . ',')
            ->line('This is an automated notification from the UCN Supply and Property Management Office (SPMO) System.')
            ->line('A request was initiated in Account Settings to update your account password.')
            ->line('Your one-time verification code (OTP) is:')
            ->line('## ' . $this->otp)
            ->line('For security purposes, this verification code is single-use and will expire in ' . $this->expiresInMinutes . ' minutes.')
            ->line('If you did not request this password change, please contact the SPMO System Administrator immediately. Your password will not be changed unless this code is verified.')
            ->salutation("This is an automated message generated by the UCN SPMO System. Please do not reply directly to this email.\n\nSupply & Property Management Office (SPMO)");
    }
}
