<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class StaffRegistrationInvitation extends Notification
{
    use Queueable;

    public function __construct(public readonly string $token)
    {
    }

    /**
     * Get the notification's delivery channels.
     *
     * @return array<int, string>
     */
    public function via(object $notifiable): array
    {
        return ['mail'];
    }

    /**
     * Get the mail representation of the notification.
     */
    public function toMail(object $notifiable): MailMessage
    {
        $registrationUrl = rtrim(config('app.url'), '/') . route('register.invitation', [
            'token' => $this->token,
            'email' => $notifiable->getEmailForPasswordReset(),
        ], false);

        return (new MailMessage)
            ->subject('[SPMO System] Automated Staff Registration Invitation')
            ->greeting('Hello ' . $notifiable->name . ',')
            ->line('This is an automated notification from the UCN Supply and Property Management Office (SPMO) System.')
            ->line('You have been authorized and invited to access the SPMO System as a staff member.')
            ->line('Please click the button below to complete your account registration.')
            ->action('Register SPMO Account', $registrationUrl)
            ->line('For security purposes, this registration link will expire in 60 minutes.')
            ->line('If you did not request this invitation or believe it was sent in error, please disregard this email.')
            ->salutation("This is an automated message generated by the UCN SPMO System. Please do not reply directly to this email.\n\nSupply & Property Management Office (SPMO)");
    }
}