import {
    Building2,
    PenTool,
    PackageSearch,
    Hash,
    Radio,
    Mail,
    ShieldCheck,
} from 'lucide-react';
import { TabMeta } from './types';

export const SETTINGS_TABS: TabMeta[] = [
    {
        id: 'institution',
        num: '01',
        label: 'Institution & Branding',
        shortLabel: 'Institution',
        description: 'Configure institutional identity, custodial office designations, and letterhead seal parameters.',
        icon: Building2,
    },
    {
        id: 'signatories',
        num: '02',
        label: 'Consumable Signatories',
        shortLabel: 'Signatories',
        description: 'Designate approving authorities, issuing custodians, and accounting officers for official forms.',
        icon: PenTool,
    },
    {
        id: 'inventory',
        num: '03',
        label: 'Stock & Reorder Rules',
        shortLabel: 'Inventory Rules',
        description: 'Define inventory thresholds, issuance safeguards, and recognized inventory units.',
        icon: PackageSearch,
    },
    {
        id: 'numbering',
        num: '04',
        label: 'Document Sequences',
        shortLabel: 'Numbering',
        description: 'Configure prefixes used for official inventory documents. Final sequence values are generated by the system.',
        icon: Hash,
    },
    {
        id: 'rfid',
        num: '05',
        label: 'RFID & Bin Storage',
        shortLabel: 'RFID',
        description: 'Configure scan debounce delays and active operating modes for stockroom RFID reader hardware.',
        icon: Radio,
    },
    {
        id: 'mail',
        num: '06',
        label: 'Email & Notifications',
        shortLabel: 'Notifications',
        description: 'Automated low-stock email triggers and outbound SMTP connectivity verification.',
        icon: Mail,
    },
    {
        id: 'operations',
        num: '07',
        label: 'Operations & Telemetry',
        shortLabel: 'Operations',
        description: 'Terminal session security, policy snapshot backups, and runtime environment telemetry.',
        icon: ShieldCheck,
    },
];
