<?php

namespace App\Providers;

use Illuminate\Auth\Notifications\ResetPassword;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Mail\Markdown;
use Illuminate\Support\Facades\Vite;
use Illuminate\Support\ServiceProvider;
use Illuminate\Validation\Rules\Password;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        app(Markdown::class)->theme('ucn');

        Password::defaults(function () {
            $rule = Password::min(12);

            return app()->environment('testing')
                ? $rule
                : $rule->mixedCase()->numbers()->symbols()->uncompromised();
        });

        ResetPassword::toMailUsing(function (object $notifiable, string $token): MailMessage {
            $resetUrl = url(route('password.reset', [
                'token' => $token,
                'email' => $notifiable->getEmailForPasswordReset(),
            ], false));

            return (new MailMessage)
                ->subject('[SPMO System] Automated Password Reset Request')
                ->greeting('Hello '.$notifiable->name.',')
                ->line('This is an automated notification from the UCN Supply and Property Management Office (SPMO) System.')
                ->line('We received a request to reset the password for your account.')
                ->action('Reset Password', $resetUrl)
                ->line('This password reset link will expire in 60 minutes.')
                ->line('If you did not request a password reset, no further action is required.')
                ->salutation("This is an automated message generated by the UCN SPMO System. Please do not reply directly to this email.\n\nSupply & Property Management Office (SPMO)");
        });

        Vite::prefetch(concurrency: 3);
    }
}
